[versions]
min-sdk = "23"
compile-sdk = "35"
target-sdk = "35"
jdk = "21"
agp = "8.7.3"
kotlin = "2.1.0"
kotlinx-coroutines = "1.10.1"
kotlinx-datetime = "0.6.1"
kotlinx-serialization = "1.7.3"
google-ksp = "2.1.0-1.0.29"
google-services = "4.4.2"
google-services-base = "18.5.0"
google-services-instantapps = "18.1.0"
google-material = "1.12.0"
google-material-compose-theme-adapter = "1.2.1"
google-firebase-analytics-ktx = "22.1.2"
google-firebase-appdistribution = "5.0.0"
google-firebase-config-ktx = "22.0.1"
google-firebase-crashlytics-plugin = "3.0.2"
google-firebase-crashlytics-ktx = "19.3.0"
google-firebase-messaging-ktx = "24.1.0"
google-play-review-ktx = "2.0.2"
google-play-app-update-ktx = "2.1.0"
huawei-services = "1.6.0.300"
androidx-appcompat = "1.7.0"
androidx-activity = "1.9.3"
androidx-benchmark = "1.3.3"
androidx-biometric-ktx = "1.2.0-alpha05"
androidx-browser = "1.8.0"
androidx-compose-animation = "1.7.6"
androidx-compose-foundation = "1.7.6"
androidx-compose-runtime = "1.7.6"
androidx-compose-ui = "1.7.6"
androidx-compose-ui-tooling-preview-desktop = "1.7.0"
androidx-compose-material = "1.7.6"
androidx-compose-material3 = "1.3.1"
androidx-core-ktx = "1.15.0"
androidx-core-splashscreen = "1.0.1"
androidx-datastore = "1.1.1"
androidx-datastore-core-okio-jvm = "1.1.1"
androidx-lifecycle = "2.8.7"
androidx-glance = "1.1.1"
androidx-palette-ktx = "1.0.0"
androidx-paging = "3.3.5"
androidx-room = "2.7.0-alpha12"
androidx-startup = "1.2.0"
androidx-sqlite = "2.5.0-SNAPSHOT"
androidx-test-ext = "1.2.1"
androidx-test-uiautomator = "2.3.0"
androidx-test-espresso = "3.6.1"
androidx-test-espresso-device = "1.0.1"
androidx-work = "2.10.0"
compose = "1.7.3"
jetbrains-androidx-navigation-compose = "2.8.0-alpha11"
jetbrains-androidx-core-bundle = "1.0.1"
detekt = "1.23.7"
spotless = "7.0.1"
coil = "2.7.0"
coil3 = "3.0.4"
okhttp = "4.12.0"
chucker = "4.1.0"
timber = "5.0.1"
javapoet = "1.13.0"
junit = "4.13.2"
palantir-git = "3.1.0"
flaker = "0.1.2"
ktor = "3.0.3"
leakcanary = "3.0-alpha-8"
koin = "4.0.1"
okio = "3.9.1"
buildkonfig = "0.15.2"
napier = "2.7.1"

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
google-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "google-services-base" }
google-services-instantapps = { module = "com.google.android.gms:play-services-instantapps", version.ref = "google-services-instantapps" }
google-play-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "google-play-review-ktx" }
google-play-app-update-ktx = { module = "com.google.android.play:app-update-ktx", version.ref = "google-play-app-update-ktx" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
google-material-compose-theme-adapter = { module = "com.google.android.material:compose-theme-adapter", version.ref = "google-material-compose-theme-adapter" }
google-firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx", version.ref = "google-firebase-analytics-ktx" }
google-firebase-config-ktx = { module = "com.google.firebase:firebase-config-ktx", version.ref = "google-firebase-config-ktx" }
google-firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx", version.ref = "google-firebase-crashlytics-ktx" }
google-firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "google-firebase-messaging-ktx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appcompat" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-benchmark-junit = { module = "androidx.benchmark:benchmark-junit4", version.ref = "androidx-benchmark" }
androidx-benchmark-macro-junit = { module = "androidx.benchmark:benchmark-macro-junit4", version.ref = "androidx-benchmark" }
androidx-biometric-ktx = { module = "androidx.biometric:biometric-ktx", version.ref = "androidx-biometric-ktx" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidx-browser" }
androidx-compose-animation = { module = "androidx.compose.animation:animation", version.ref = "androidx-compose-animation" }
androidx-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "androidx-compose-foundation" }
androidx-compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "androidx-compose-foundation" }
androidx-compose-material-ripple = { module = "androidx.compose.material:material-ripple", version.ref = "androidx-compose-material" }
androidx-compose-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "androidx-compose-material" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "androidx-compose-material3" }
androidx-compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "androidx-compose-runtime" }
androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview-android = { module = "androidx.compose.ui:ui-tooling-preview-android", version.ref = "androidx-compose-ui" }
androidx-compose-ui-tooling-preview-desktop = { module = "androidx.compose.ui:ui-tooling-preview-desktop", version.ref = "androidx-compose-ui-tooling-preview-desktop" }
androidx-compose-ui-util = { module = "androidx.compose.ui:ui-util", version.ref = "androidx-compose-ui" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidx-core-ktx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "androidx-core-splashscreen" }
androidx-datastore-core = { module = "androidx.datastore:datastore-core", version.ref = "androidx-datastore" }
androidx-datastore-core-okio-jvm = { module = "androidx.datastore:datastore-core-okio-jvm", version.ref = "androidx-datastore-core-okio-jvm" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "androidx-datastore" }
androidx-datastore-preferences-core = { module = "androidx.datastore:datastore-preferences-core", version.ref = "androidx-datastore" }
androidx-glance-appwidget = { module = "androidx.glance:glance-appwidget", version.ref = "androidx-glance" }
androidx-glance-material3 = { module = "androidx.glance:glance-material3", version.ref = "androidx-glance" }
androidx-lifecycle-common = { module = "androidx.lifecycle:lifecycle-common", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "androidx-lifecycle" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "androidx-palette-ktx" }
androidx-paging-common-ktx = { module = "androidx.paging:paging-common-ktx", version.ref = "androidx-paging" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "androidx-paging" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "androidx-room" }
androidx-startup-runtime = { module = "androidx.startup:startup-runtime", version.ref = "androidx-startup" }
androidx-sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "androidx-sqlite" }
androidx-test-ext-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }
androidx-test-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }
androidx-espresso-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version.ref = "androidx-test-espresso" }
androidx-test-espresso-device = { module = "androidx.test.espresso:espresso-device", version.ref = "androidx-test-espresso-device" }
androidx-test-espresso-idling-resource = { module = "androidx.test.espresso:espresso-idling-resource", version.ref = "androidx-test-espresso" }
androidx-test-uiautomator = { module = "androidx.test.uiautomator:uiautomator", version.ref = "androidx-test-uiautomator" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "androidx-work" }
jetbrains-androidx-navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "jetbrains-androidx-navigation-compose" }
jetbrains-androidx-core-bundle = { module = "org.jetbrains.androidx.core:core-bundle", version.ref = "jetbrains-androidx-core-bundle" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil3-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil3-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
chucker-library = { module = "com.github.chuckerteam.chucker:library", version.ref = "chucker" }
chucker-library-no-op = { module = "com.github.chuckerteam.chucker:library-no-op", version.ref = "chucker" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }
junit = { module = "junit:junit", version.ref = "junit" }
flaker-android-okhttp = { module = "io.github.rotbolt:flaker-android-okhttp", version.ref = "flaker" }
flaker-android-okhttp-noop = { module = "io.github.rotbolt:flaker-android-okhttp-noop", version.ref = "flaker" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
leakcanary = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary" }
koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kotlin-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[bundles]
kotlinx-coroutines-common = [
    "kotlinx-coroutines-core"
]
kotlinx-datetime-common = [
    "kotlinx-datetime"
]
kotlinx-serialization-common = [
    "kotlinx-serialization-json"
]
jetbrains-androidx-navigation-compose-common = [
    "jetbrains-androidx-navigation-compose"
]
jetbrains-androidx-core-bundle-common = [
    "jetbrains-androidx-core-bundle"
]
datastore-common = [
    "androidx-datastore-core",
    "androidx-datastore-preferences-core"
]
lifecycle-common = [
    "androidx-lifecycle-common"
]
room-common = [
    "androidx-room-runtime",
    "androidx-room-paging"
]
room-paging-common = [
    "androidx-room-paging"
]
room-compiler-common = [
    "androidx-room-compiler"
]
sqlite-common = [
    "androidx-sqlite-bundled"
]
ktor-common = [
    "ktor-client-core",
    "ktor-client-cio",
    "ktor-client-content-negotiation",
    "ktor-serialization-kotlinx-json"
]
koin-common = [
    "koin-compose",
    "koin-compose-viewmodel"
]
coil-common = [
    "coil3-compose",
    "coil3-network-ktor3"
]
okio-common = [
    "okio"
]
napier-common = [
    "napier"
]

kotlinx-coroutines-android = [
    "kotlinx-coroutines-android"
]
kotlin-reflect-android = [
    "kotlin-reflect"
]
activity-android = [
    "androidx-activity-compose"
]
appcompat-android = [
    "androidx-appcompat",
    "androidx-appcompat-resources"
]
benchmark-android = [
    "androidx-benchmark-junit"
]
benchmark-macro-android = [
    "androidx-benchmark-macro-junit"
]
biometric-android = [
    "androidx-biometric-ktx"
]
browser-android = [
    "androidx-browser"
]
compose-android = [
    "androidx-compose-animation",
    "androidx-compose-foundation",
    "androidx-compose-foundation-layout",
    #"androidx-compose-material-ripple",
    "androidx-compose-material-icons-extended",
    "androidx-compose-material3",
    "androidx-compose-runtime",
    "androidx-compose-ui",
    "androidx-compose-ui-tooling",
    "androidx-compose-ui-tooling-preview-android",
    "androidx-compose-ui-util"
]
core-android = [
    "androidx-core-ktx"
]
core-splashscreen-android = [
    "androidx-core-splashscreen"
]
datastore-android = [
    "androidx-datastore-preferences"
]
glance-android = [
    "androidx-glance-appwidget",
    "androidx-glance-material3"
]
lifecycle-android = [
    "androidx-lifecycle-runtime-compose",
    "androidx-lifecycle-process"
]
paging-android = [
    "androidx-paging-compose"
]
palette-android = [
    "androidx-palette-ktx"
]
startup-android = [
    "androidx-startup-runtime"
]
test-espresso-android = [
    "androidx-test-espresso-core",
    "androidx-espresso-test-espresso-contrib",
    "androidx-test-espresso-device",
    "androidx-test-espresso-idling-resource"
]
test-ext-junit-android = [
    "androidx-test-ext-junit-ktx"
]
test-uiautomator-android = [
    "androidx-test-uiautomator"
]
work-android = [
    "androidx-work-runtime-ktx"
]
ktor-android = [
    "ktor-client-okhttp",
    "ktor-client-android"
]
koin-android = [
    "koin-android",
    "koin-androidx-compose",
    "koin-androidx-workmanager"
]
coil-android = [
    "coil-compose"
]
timber-android = [
    "timber"
]
google-firebase-android = [
    "google-firebase-analytics-ktx",
    "google-firebase-config-ktx",
    "google-firebase-crashlytics-ktx",
    "google-firebase-messaging-ktx"
]
google-services-android = [
    "google-services-base",
    "google-services-instantapps"
]
google-services-instantapps-android = [
    "google-services-instantapps"
]
google-material-android = [
    "google-material",
    "google-material-compose-theme-adapter"
]
google-play-android = [
    "google-play-review-ktx",
    "google-play-app-update-ktx"
]
leakcanary-android = [
    "leakcanary"
]
okhttp-logging-interceptor-android = [
    "okhttp-logging-interceptor"
]
chucker-library-android = [
    "chucker-library"
]
chucker-library-no-op-android = [
    "chucker-library-no-op"
]
javapoet-android = [
    "javapoet"
]
junit-android = [
    "junit"
]
flaker-android = [
    "flaker-android-okhttp"
]
flaker-noop-android = [
    "flaker-android-okhttp-noop"
]

kotlinx-coroutines-desktop = [
    "kotlinx-coroutines-swing"
]
compose-desktop = [
    "androidx-compose-ui-tooling-preview-desktop"
]
datastore-desktop = [
    "androidx-datastore-core-okio-jvm"
]
paging-desktop = [
    "androidx-paging-common-ktx"
]

sqlite-bundled-ios = [
    "androidx-sqlite-bundled"
]
ktor-ios = [
    "ktor-client-darwin"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
android-dynamic-feature = { id = "com.android.dynamic-feature", version.ref = "agp" }
android-test = { id = "com.android.test", version.ref = "agp" }
androidx-room = { id = "androidx.room", version.ref = "androidx-room" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-cocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
google-ksp = { id = "com.google.devtools.ksp", version.ref = "google-ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
google-firebase-appdistribution = { id = "com.google.firebase.appdistribution", version.ref = "google-firebase-appdistribution" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "google-firebase-crashlytics-plugin" }
huawei-services = { id = "com.huawei.agconnect", version.ref = "huawei-services" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
palantir-git = { id = "com.palantir.git-version", version.ref = "palantir-git" }
buildkonfig = { id = "com.codingfeline.buildkonfig", version.ref = "buildkonfig" }